site_name: Frontira
theme: material

pages:
  - Home: index.md
  - Getting Started: getting-started.md
  - Downloads: downloads.md
  - Tutorials:
    - Overview: tutorials/overview.md
    - Hello Frontira: tutorials/hello-frontira.md
    - Core: tutorials/core.md
    - Authorization: tutorials/authorization.md
    - Data Loading: tutorials/data-loading.md
    - Document Distribution: tutorials/document-distribution.md
    - Monitoring and Scaling: tutorials/monitoring-and-scaling.md
  - Documentation:
    - Services:
      - QIX Engine: documentation/services/qix-engine.md
      - License Service: documentation/services/license-service.md
      - Mira: documentation/services/mira.md
    - Contract: documentation/contract.md
    - APIs: documentation/apis.md
  - Use Cases:
    - Overview: use-cases/overview.md
    - Custom Analytics UI: use-cases/use-case-custom-analytics/README.md
  - Support & Services:
    - Licensing: support-and-services/licensing.md
    - Sales: support-and-services/sales.md
    - Technical Support: support-and-services/tech-support.md
    - Training: support-and-services/training.md
  - Pricing: pricing.md
