site_name: Qlik Core

theme:
  name: 'material'
  logo: 'images/QlikCore-Horizontal-Print-white.svg'
  custom_dir: 'theme'
  favicon: 'images/favicon.ico'

extra_css:
  - 'stylesheets/custom-style.css'
  - 'stylesheets/downloads.css'
extra_javascript:
  - 'javascripts/extra.js'
  - 'https://unpkg.com/enigma.js@2.2.1/enigma.min.js'
  - 'javascripts/downloads.js'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/qlik-oss/core-website'
    - type: 'slack'
      link: 'http://branch.qlik.com/slack'

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      base_path: ./
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

repo_name: 'qlik-oss/core-website'
repo_url: 'https://github.com/qlik-oss/core-website'
edit_uri: edit/master/docs
google_analytics: ['UA-110266862-2', 'auto']

pages:
  - Home: index.md
  - Get Started: get-started.md
  - Downloads: downloads.md
  - Licensing: licensing.md
  - Beta agreement: beta.md
  - Use Cases: use-cases.md
  - Tutorials:
    - Hello Engine: tutorials/hello-engine.md
    - Hello Data: tutorials/hello-data.md
    - Hello Visualization: tutorials/hello-visualization.md
    - Orchestration: tutorials/orchestration.md
    - Authorization: tutorials/authorization.md
    - Data Loading: tutorials/data-loading.md
  - Services:
    - Mira: services/mira.md
    - Qlik Associative Engine:
      - Introduction: services/qix-engine/introduction.md
      - Access Control: services/qix-engine/access-control.md
      - Document Synchronization: services/qix-engine/doc-synchronization.md
      - Logging: services/qix-engine/logging.md
      - Resource Management: services/qix-engine/resource-management.md
      - QIX API:
        - Introduction: services/qix-engine/apis/qix/introduction.md
        - Definitions: services/qix-engine/apis/qix/definitions.md
        - Global: services/qix-engine/apis/qix/global.md
        - Doc: services/qix-engine/apis/qix/doc.md
        - Generic Object: services/qix-engine/apis/qix/genericobject.md
        - Generic Bookmark: services/qix-engine/apis/qix/genericbookmark.md
        - Generic Dimension: services/qix-engine/apis/qix/genericdimension.md
        - Generic Measure: services/qix-engine/apis/qix/genericmeasure.md
        - Generic Variable: services/qix-engine/apis/qix/genericvariable.md
        - Field: services/qix-engine/apis/qix/field.md
        - Variable: services/qix-engine/apis/qix/variable.md
      - Data Connector API:
        - Introduction: services/qix-engine/apis/data-loading/introduction.md
        - API Specification: services/qix-engine/apis/data-loading/data-connector-api.md
      - Analytical Connector API: services/qix-engine/apis/server-side-extension/analytical-connector-api.md
      - Rest API: services/qix-engine/apis/rest/qlik-associative-engine-api.md
    - Licenses: services/licenses.md
  - Conventions:
    - Introduction: conventions/introduction.md
    - API Strategy: conventions/api-strategy.md
    - Logging: conventions/logging.md
    - Metrics: conventions/metrics.md
  - Third Party Licenses: third-party-licenses.md
  - License Registration: license-registration.md
  