site_name: Qlik Core

theme:
  name: 'material'
  logo: 'images/QlikCore-Horizontal-Print-white.svg'
  custom_dir: 'theme'
  favicon: 'images/favicon.ico'

extra_css:
  - 'stylesheets/custom-style.css'
extra_javascript:
  - 'javascripts/extra.js'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/qlik-ea/info'
    - type: 'slack'
      link: 'http://qlikbranch-slack-invite.herokuapp.com/'

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

repo_name: 'qlik-ea/info'
repo_url: 'https://github.com/qlik-ea/info'
google_analytics: ['UA-110266862-1', 'ca.qliktive.com']

pages:
  - startpage: index.md
  - Beta: beta.md
  - Documentation:
    - Home: home.md
    - Getting Started: getting-started.md
    - Downloads: downloads.md
    - Tutorials:
      - Hello Engine: tutorials/hello-engine.md
      - Hello Data: tutorials/hello-data.md
      - Hello Visualization: tutorials/hello-visualization.md
      - Orchestration: tutorials/orchestration.md
      - Authorization: tutorials/authorization.md
      - Data Loading: tutorials/data-loading.md
      - Document Distribution: tutorials/document-distribution.md
      - Scalability:
        - Overview: tutorials/scalability/overview.md
        - Newspaper website: tutorials/scalability/newspaper.md
    - Services:
      - QIX Engine:
        - Introduction: documentation/services/qix-engine/introduction.md
        - Access Control: documentation/services/qix-engine/access-control.md
        - Logging: documentation/services/qix-engine/logging.md
        - Resource Management: documentation/services/qix-engine/resource-management.md
        - QIX API: 
          - Introduction: documentation/services/qix-engine/apis/qix/introduction.md
          - Definitions: documentation/services/qix-engine/apis/qix/definitions.md
          - Global: documentation/services/qix-engine/apis/qix/global.md
          - Doc: documentation/services/qix-engine/apis/qix/doc.md
          - Generic Object: documentation/services/qix-engine/apis/qix/genericobject.md
          - Generic Bookmark: documentation/services/qix-engine/apis/qix/genericbookmark.md
          - Generic Derived Field: documentation/services/qix-engine/apis/qix/genericderivedfields.md
          - Generic Dimension: documentation/services/qix-engine/apis/qix/genericdimension.md
          - Generic Measure: documentation/services/qix-engine/apis/qix/genericmeasure.md
          - Generic Variable: documentation/services/qix-engine/apis/qix/genericvariable.md
          - Field: documentation/services/qix-engine/apis/qix/field.md
          - Variable: documentation/services/qix-engine/apis/qix/variable.md
        - Data Loading API: documentation/services/qix-engine/apis/data-loading/data-loading.md
      - License Service: documentation/services/license-service.md
      - Mira: documentation/services/mira.md
    - Contract: documentation/contract.md
    - API Strategy: documentation/api-strategy.md
    - Support & Services:
      - Licensing: support-and-services/licensing.md
      - Sales: support-and-services/sales.md
      - Technical Support: support-and-services/tech-support.md
      - Training: support-and-services/training.md
