site_name: Frontira
theme: material

pages:
  - Home: index.md
  - Getting Started:
    - Prerequisites: getting-started/prerequisites.md
    - Download: getting-started/download.md
  - Documentation:
    - Services:
      - QIX Engine: documentation/services/qix-engine.md
      - License Service: documentation/services/license-service.md
      - Mira: documentation/services/mira.md
    - Contract: documentation/contract.md
    - Recipes:      
      - Overview: documentation/recipes/overview.md
      - Authorization: documentation/recipes/authorization.md
      - Core: documentation/recipes/core.md
      - Data Loading: documentation/recipes/data-loading.md
      - Document Distribution: documentation/recipes/document-distribution.md
      - Monitoring and Scaling: documentation/recipes/monitoring-and-scaling.md
    - APIs: documentation/apis.md
  - Use Cases:
    - Overview: use-cases/overview.md
    - Custom Analytics UI: use-cases/use-case-custom-analytics/README.md
  - Terminology: terminology.md
  - Support & Services:
    - Licensing: support-and-services/licensing.md
    - Sales: support-and-services/sales.md
    - Technical Support: support-and-services/tech-support.md
    - Training: support-and-services/training.md
  - Pricing: pricing.md
