# version: 2
# jobs:
#   build:
#     docker:
#       - image: docker:17.10.0-ce
#     steps:
#       - checkout
#      - restore_cache:
#          key: dependency-cache-{{ checksum "package.json" }}
      # - setup_remote_docker
      # - run:
      #     name: Build the site
      #     command: ./build.sh
      # Persist to workspace so other jobs in the workflow can reuse artifacts
      # - persist_to_workspace:
      #     root: workspace
      #     paths:
      #       - version.txt
      #       - mira_image.tar

version: 2
jobs:
  build:
    machine: true
    working_directory: ~/info
    steps:
      - checkout
      - run:
          name: Build the site
          command: ./build.sh
      - store_artifacts:
          path: ./site
