version: 2
jobs:
  build:
    machine: true
    working_directory: ~/info
    steps:
      - checkout
      - run:
          name: Build the site
          command: ./build.sh
      - store_artifacts:
          path: ./site
