version: 2
jobs:
  build:
    machine: true
    working_directory: ~/info
    steps:
      - checkout
      - run:
          name: Set edit URL
          command: grep -rl edit_uri ./mkdocs.yml | xargs sed -i "s:/master:/$CIRCLE_BRANCH:g" 
      - run:
          name: Lint the documentation
          command: ./lint.sh
      - run:
          name: Build the site
          command: ./build.sh
      - store_artifacts:
          path: ./site
      - run:
          name: Deploy the site for review
          command: |
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              export BUILD_NUMBER=$CIRCLE_BUILD_NUM
              export BRANCH_NAME=$CIRCLE_BRANCH	
              export SHA=$CIRCLE_SHA1
              .circleci/deploy.sh
            fi
      - run:
          name: Sync documentation to S3 bucket
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              aws s3 sync site/ s3://qlikcoresite/ --delete
              aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'
            fi

