version: 2
jobs:
  lint:
    docker:
    - image: node:8
    working_directory: ~/info
    steps:
      - checkout
      - run:
          name: Install markdownlint-cli
          command: npm install -g markdownlint-cli
      - run:
          name: Lint the markdowns
          command: markdownlint ./docs
  build:
    machine: true
    working_directory: ~/info
    steps:
      - checkout
      - run:
          name: Build the site
          command: ./build.sh
      - store_artifacts:
          path: ./site

workflows:
  version: 2
  lint_and_build:
    jobs:
      - lint
      - build:
          requires:
            - lint
