version: 2
jobs:
  build:
    machine: true
    working_directory: ~/info
    steps:
      - checkout
      - run:
          name: Set edit URL
          command: grep -rl edit_uri ./mkdocs.yml | xargs sed -i "s:/master:/$CIRCLE_BRANCH:g" 
      - run:
          name: Lint the documentation
          command: ./lint.sh
      - run:
          name: Build the site
          command: ./build.sh
      - store_artifacts:
          path: ./site
      - run:
          name: Deploy the site
          command: |
            export BUILD_NUMBER=$CIRCLE_BUILD_NUM
            export BRANCH_NAME=$CIRCLE_BRANCH
            .circleci/deploy.sh
