linters:
  - markdownlint . # Markdown syntax linting
  # The magic parameter filters out all files that has 'proselint-disable' in them
  - proselint $(grep -L "proselint-disable" -r . | grep .md) # English prose linting
